### ISSUE TITLE
Obligation to have a picture at the bottom before posting

### ISSUE THREAD

**Issue by AbellDesign16a** [joseph-abell/abelldesign#13]
# Bug report
It won't let me post a blog post unless there is an image at the bottom. 

**If the current behavior is a bug, please provide the steps to reproduce. How to navigate to the page, what do i need to do on the page to see the bug. **

**What is the expected behavior?**

**Other relevant information:**

I love you.

**Comment by joseph-abell** [comment]
I've made most of the images optional. Check the change on the website, first time when you remove an image, just to make sure the bage doesn't break. should be fine.
