### ISSUE TITLE
Service Page: Images are rendered in their blurry format, and do not render as the full resolution

### ISSUE THREAD

**Issue by joseph-abell** [joseph-abell/abelldesign#6]
# Bug report

**What is the current behaviour?**
Images are rendered in their blurry format, and do not render as their full resolution

**If the current behaviour is a bug, please provide the steps to reproduce. How to navigate to the page, what do i need to do on the page to see the bug. **
- Go to the service page on the front-end
- see that the images are blurry

**What is the expected behaviour?**
images should load in their full resolution.

**Other relevant information:**

**Comment by joseph-abell** [comment]
Assigned to Grace as I could not reproduce. Can you close this ticket if you are happy with it?

**Comment by AbellDesign16a** [comment]
This is a case study, but example here

**Comment by joseph-abell** [comment]
Your example did not include a link

**Comment by AbellDesign16a** [comment]
![Screenshot_20210101-134314](https://user-images.githubusercontent.com/76840647/103439803-0c1c6880-4c38-11eb-94d4-055ea1bc157c.png)

**Comment by joseph-abell** [comment]
the fix for this is in progress. I've not been able to replicate, but in a classic case of baby with bathwater, let's rip out the architecture and start again. Moving away from Gatsby and towards Next.js
