### ISSUE TITLE
Italics are not styled correctly.

### ISSUE THREAD

**Issue by joseph-abell** [joseph-abell/abelldesign#7]
# Bug report

**What is the current behaviour?**
When I try to apply italics, the text is rendered with a *, rather than as an italic.

**If the current behaviour is a bug, please provide the steps to reproduce. How to navigate to the page, what do i need to do on the page to see the bug. **

No information given about where to reproduce.

**What is the expected behaviour?**

Render text in italics.

**Other relevant information:**

**Comment by joseph-abell** [comment]
More information is needed for me to do any work on this. assigned to Grace to give me concrete examples where this is happening.

There could be two scenarios here. Either, you are applying markdown formatting to a field which does not support markdown, or you are using a markdown field, but the template isn't set up to translate that into html. Without specific examples, I can't tell which fix to aply.

**Comment by AbellDesign16a** [comment]
![Screenshot_20210101-134641](https://user-images.githubusercontent.com/76840647/103439811-18a0c100-4c38-11eb-97ec-bfe0fac887ca.png)

**Comment by joseph-abell** [comment]
I've pushed a fix to the case studies pages. If this is happening elsewhere, reopen the ticket.

**Comment by joseph-abell** [comment]
As a note, I might need to do a bit of training, this issue was due to poor markdown input. Not your fault, but we night need to run some cleanup in the markdown tab when entering data
