### ISSUE TITLE
Missing Favicons

### ISSUE THREAD

**Issue by joseph-abell** [joseph-abell/abelldesign#9]
# Bug report

**What is the current behavior?**
We have missing favicons.

**What is the expected behavior?**
We have favicons

**Other relevant information:**
Can we have PNGs of 16x16 px, 23x32 px, 64x64 px 180x180 px. And can I have an SVG with a transparent background, black vector lines, and a hex colour we want safari to turn the black lines to?

**Comment by AbellDesign16a** [comment]
Hex 15a796
